### ISSUE TITLE
How should we find the public ADYEN_KEY from an e-commerce website?

### ISSUE THREAD

**Issue by kk-deng** [66niko99/py-adyen-encrypt#2]
Thank you so much for your work!

I have been trying to make an app to submit orders on a website but got blocked by Adyen client-side encryption for a long time. Now it's using 0_1_25 version, and I can't find the public key from the js files. Is there any way to get the Adyen key from the website?

Any suggestions would be appreciated!

**Comment by grinchify** [comment]
enter the card details and then inspect webpage. and search for "key"

**Comment by haune2311** [comment]
![image](https://user-images.githubusercontent.com/65016652/231738343-cf42b246-5b67-4bf8-bf97-0e229035354e.png)

now adyen have version 1 can u update it?

infomation: {"alg":"RSA-OAEP","enc":"A256CBC-HS512","version":"1"}

**Comment by grinchify** [comment]
Thats not the version thats the key prefix. Look at the actual encrypted ayden value and the prefix of that tells you the version.

**Comment by haune2311** [comment]
> Thats not the version thats the key prefix. Look at the actual encrypted ayden value and the prefix of that tells you the version.

I'm trying but not match new version of Adyen, something has charged.

**Comment by grinchify** [comment]
What site is it on?

**Comment by haune2311** [comment]
> What site is it on?

can I have your contact, telegram or any I want ask something more...

**Comment by grinchify** [comment]
Grinch#0001 - discord
